<?xml version="1.0" encoding="UTF-8"?><testrun name="PotServiceTest" project="demo" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="com.example.demo.service.PotServiceTest" time="1.389" displayname="PotServiceTest" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.PotServiceTest]">
    <testcase name="iAddNewSuccessfully" classname="com.example.demo.service.PotServiceTest" time="1.349" displayname="I add new successfully" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.PotServiceTest]/[method:iAddNewSuccessfully()]"/>
    <testcase name="potAlreadyExistsInlist" classname="com.example.demo.service.PotServiceTest" time="0.04" displayname="potAlreadyExistsInlist()" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.PotServiceTest]/[method:potAlreadyExistsInlist()]">
      <failure>
        <expected>class com.example.demo.service.exception.ResourceNotFoundException</expected>
        <actual>class com.example.demo.service.exception.ResourceAlreadyExists</actual>
        org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;com.example.demo.service.exception.ResourceNotFoundException&gt; but was: &lt;com.example.demo.service.exception.ResourceAlreadyExists&gt;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at com.example.demo.service.PotServiceTest.potAlreadyExistsInlist(PotServiceTest.java:87)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: com.example.demo.service.exception.ResourceAlreadyExists: Resource already exists
	at com.example.demo.service.PotService.newPot(PotService.java:32)
	at com.example.demo.service.PotServiceTest.lambda$0(PotServiceTest.java:87)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more


      </failure>
    </testcase>
  </testsuite>
</testrun>
