<?xml version="1.0" encoding="UTF-8"?><testrun name="FriendServiceTest" project="demo" tests="4" started="4" failures="1" errors="0" ignored="0">
  <testsuite name="com.example.demo.service.FriendServiceTest" time="1.392" displayname="FriendServiceTest" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]">
    <testcase name="veryShortName" classname="com.example.demo.service.FriendServiceTest" time="1.353" displayname="very short name" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:veryShortName()]">
      <failure>
        <expected>class com.example.demo.service.exception.InvalidField</expected>
        <actual>class com.example.demo.service.exception.ResourceNotFoundException</actual>
        org.opentest4j.AssertionFailedError: Unexpected exception type thrown, expected: &lt;com.example.demo.service.exception.InvalidField&gt; but was: &lt;com.example.demo.service.exception.ResourceNotFoundException&gt;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:67)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at com.example.demo.service.FriendServiceTest.veryShortName(FriendServiceTest.java:146)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: com.example.demo.service.exception.ResourceNotFoundException: Rource not found. id Friend not found
	at com.example.demo.service.FriendService.lambda$1(FriendService.java:57)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.example.demo.service.FriendService.editFriend(FriendService.java:57)
	at com.example.demo.service.FriendServiceTest.lambda$1(FriendServiceTest.java:147)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:53)
	... 6 more


      </failure>
    </testcase>
    <testcase name="addedFriendSuccessfully" classname="com.example.demo.service.FriendServiceTest" time="0.024" displayname="added friend successfully" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:addedFriendSuccessfully()]"/>
    <testcase name="friendAlreadyExists" classname="com.example.demo.service.FriendServiceTest" time="0.006" displayname="friend already exists" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:friendAlreadyExists()]"/>
    <testcase name="editedSuccessfully" classname="com.example.demo.service.FriendServiceTest" time="0.008" displayname="edited successfully" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:editedSuccessfully()]"/>
  </testsuite>
</testrun>
